### ISSUE TITLE
Window titlebars are white now, using numix

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/deepin-kwin#35]
I've been using Numix as a theme since I used dde on my arch linux. 
Now with moving to kwin all window titles are white instead of that dark grey what numix usually brought. The menu is still in that color though.

Chrome, title white - wrong
![image](https://user-images.githubusercontent.com/6298761/65492421-3027c080-deb1-11e9-8e64-9081f197cba9.png)

Rambox, title white, but menu correct
![image](https://user-images.githubusercontent.com/6298761/65492628-885ec280-deb1-11e9-8569-22044be2ad65.png)

**Comment by BLumia** [comment]
If you are sure you are using deepin-kwin, switching theme to dark should also set your titlebar to dark. If you did change the look and feel via (KDE's) `systemsettings`, consider backup and remove your kwinrc file first :)

**Comment by DasJott** [comment]
I am pretty sure I am using deepin-kwin.
If I used the light deepin theme before, the titles keep being light. If I use the dark before, they keep being dark.
The dark deepin theme is a bit too dark in my opinion and that numix theme matches best what I like.

**Comment by BLumia** [comment]
If current deepin-kwin default look'n'feel doesn't fit your requirement, you can also try install `systemsettings` and some 3rd-party kwin theme, and then you can select other kwin themes via the KDE `systemsettings` application (since it will allow you tweak the kwin settings). But as a reminder, deepin-kwin did some changes on kwin behavior and not all settings from the systemsettings app will works, so before you do that, consider backup your kwinrc file first.

**Comment by DasJott** [comment]
I already tried `systemsettings` and I wasn't all that satisfied with that either. 
It is not that hard to take the black window borders with the rest following numix theme. I' ll trust in you improving the new deepin-kwin more and more so that those problems will be vanished at some point.

I really hope you will keep the deepin look and feel, even though you move to K world...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
